## This is a template for the openid container
## Documentation about the ory container can be found here: https://www.ory.sh/docs/hydra/
## This container is used to manage the authentication and authorization of the application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openid
  namespace: backend
  labels:
    name: openid
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openid
  template:
    metadata:
      labels:
        name: openid
    spec:
      containers:
      - name: openid
        image: oryd/hydra:v1.10.6
        ports: 
        - containerPort: 5444
        env:
        - name: SECRETS_SYSTEM
          value: myrandomvalue1234567890
        - name: DSN
          value: postgres://libary:secret@database.backend.svc.cluster.local:5432/libary?sslmode=disable
        - name: URLS_SELF_ISSUER
          value: https://openid.backend.svc.cluster.local:5444/
        - name: URLS_LOGIN
          value: http://openid.backend.svc.cluster.local:5444/oauth2/auth
        - name: URLS_CONSENT
          value: http://openid.backend.svc.cluster.local:5444/oauth2/auth/requests/consent
        # Just spin & wait forever
        command: [ "hydra" ]
        args: [ "serve", "all" ]
      initContainers:
        - name: openid-migration
          image: oryd/hydra:v1.10.6
          env:
          - name: SECRETS_SYSTEM
            value: myrandomvalue1234567890 
          - name: DSN
            value: postgres://libary:secret@database.backend.svc.cluster.local:5432/libary?sslmode=disable
          command: ["hydra"]
          args: ["migrate", "sql", "--yes", "--read-from-env"]
---
apiVersion: v1
kind: Service
metadata:
  name: openid
  namespace: backend
  labels:
    name: openid
spec:
  type: NodePort
  ports:
  - name: openid-introspect
    port: 4444
    targetPort: 4444
    nodePort: 30000
  - name: openid-authorize 
    port: 4445
    targetPort: 4445
    nodePort: 30001
  selector:
    name: openid
