# This is a template for the openid container
## Documentation about the ory container can be found here: https://www.ory.sh/docs/hydra/
## This container is used to manage the authentication and authorization of the application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.openid.name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.openid.name }}-deployment
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      name: {{ .Values.openid.name }}-pod
  template:
    metadata:
      labels:
        name: {{ .Values.openid.name }}-pod
    spec:
      containers:
      - name: {{ .Values.openid.name }}-container
        image: {{ .Values.openid.image }}
        ports: 
        - name: "introspect-port"
          containerPort: {{ .Values.openid.ports.introspect.targetPort }}
        - name: "authorize-port"
          containerPort: {{ .Values.openid.ports.authorize.targetPort }}
        env:
        - name: SECRETS_SYSTEM
          value: {{ .Values.openid.secrets.system }}
        - name: DSN
          value: "postgres://{{ .Values.postgres.db }}:{{ .Values.postgres.secret }}@{{ .Values.postgres.name }}-svc.{{ .Release.Namespace }}.svc.cluster.local:5432/libary?sslmode=disable"
        - name: URLS_SELF_ISSUER
          value: "https://{{ .Values.openid.name }}-svc.{{ .Release.Namespace }}.svc.cluster.local:4444/"
        - name: URLS_LOGIN
          value: "http://{{ .Values.openid.name }}-svc.{{ .Release.Namespace }}.svc.cluster.local:4444/oauth2/auth"
        - name: URLS_CONSENT
          value: "http://{{ .Values.openid.name }}-svc.{{ .Release.Namespace }}.svc.cluster.local:4444/oauth2/auth/requests/consent"
        # Just spin & wait forever
        command: [ "hydra" ]
        args: [ "serve", "all" ]
      initContainers:
        - name: openid-migration-container
          image: {{ .Values.openid.image }}
          env:
          - name: SECRETS_SYSTEM
            value: {{ .Values.openid.secrets.system }}
          - name: DSN
            value: "postgres://{{ .Values.postgres.db }}:{{ .Values.postgres.secret }}@{{ .Values.postgres.name }}-svc.{{ .Release.Namespace }}.svc.cluster.local:5432/libary?sslmode=disable"
          command: ["hydra"]
          args: ["migrate", "sql", "--yes", "--read-from-env"]
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.openid.name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.openid.name }}-svc
spec:
  type: NodePort
  ports:
  - name: "{{ .Values.openid.name }}-introspect"
    port: {{ .Values.openid.ports.introspect.port }}
    targetPort: {{ .Values.openid.ports.introspect.targetPort }}
    nodePort: {{ .Values.openid.ports.introspect.nodePort }}
  - name: "{{ .Values.openid.name }}-authorize"
    port: {{ .Values.openid.ports.authorize.port }}
    targetPort: {{ .Values.openid.ports.authorize.targetPort }}
    nodePort: {{ .Values.openid.ports.authorize.nodePort }}
  selector:
    name: {{ .Values.openid.name }}-pod
